### ISSUE TITLE
Multithreading issue in InfiniteChannel Len()

### ISSUE THREAD

**Issue by freak82** [eapache/channels#18]
I think there is multithreading issue with the InfiniteChannel Len().
The problem is that the ch.buffer is manipulated in the infiniteBuffer() go routine, but the ch.buffer.Length() could be called from a different go routine through InfiniteChannel Len().
As far as I checked the queue.Queue container is not thread safe, neither is its length variable.

**Comment by eapache** [comment]
Yes, you are correct. The queue package is explicitly not thread-safe, and it didn't occur to me that `Len` on the channel might be called in a separate goroutine, but of course that is totally reasonable. I'll see if I can find a solution that doesn't negatively impact performance.

**Comment by eapache** [comment]
Upon further investigation this is a bigger issue than I thought:
- this affects the `Len()` method of all the channel implementations here except (of course) the `NativeChannel`
- this also affects the `Cap()` method of the `ResizableChannel`
- this also potentially causes stale reads in the single-threaded "write a value then read the length" case where the length value may not be updated yet depending on the scheduler

Considerations:
- simply accessing the length/size variables atomically is not correct, it solves the data race but not the stale reads
- reading the length off a channel (and feeding it in the same `select` call in the helper goroutines) works but causes a severe performance regression and makes shutdown leak a goroutine since *something* has to continually feed the length channel (it is legitimate to call `len` on a closed channel)

**Comment by eapache** [comment]
Oh of course, reading from a closed channel yields the appropriate zero of that type, so if I close the new length channel that solves the leak, though not the performance hit.

**Comment by eapache** [comment]
Thanks for the report!
